import { OriginBeatDefinition } from "./types";

export const originBeats: OriginBeatDefinition[] = [
  {
    id: "question",
    chapterLabel: "Question",
    title: "Question Zero",
    line: "Is life on Earth unique?",
    textMode: "overlay",
    scrollWeight: 0.92,
    entryTransitionPct: 0.2,
    holdPct: 0.56,
    exitTransitionPct: 0.24,
    assetSlot: "quantum-question-field",
  },
  {
    id: "atoms",
    chapterLabel: "Emergence",
    title: "Emergence",
    line: "Life is the emergence of smaller pieces and rules: molecules, physics, chemistry, and energy.",
    textMode: "emissive",
    scrollWeight: 1.24,
    entryTransitionPct: 0.18,
    holdPct: 0.58,
    exitTransitionPct: 0.24,
    assetSlot: "atomic-emergence",
  },
  {
    id: "network",
    chapterLabel: "Consciousness",
    title: "Consciousness",
    line: "Where exactly does consciousness emerge from?",
    textMode: "overlay",
    scrollWeight: 1,
    entryTransitionPct: 0.18,
    holdPct: 0.56,
    exitTransitionPct: 0.26,
    assetSlot: "neural-emergence-network",
  },
  {
    id: "eye",
    chapterLabel: "Presence",
    title: "Presence",
    line: "What does it mean for us to be here, together?",
    textMode: "overlay",
    scrollWeight: 1.16,
    entryTransitionPct: 0.17,
    holdPct: 0.59,
    exitTransitionPct: 0.24,
    assetSlot: "human-eye-macro",
  },
  {
    id: "planet",
    chapterLabel: "Trajectory",
    title: "Trajectory",
    line: "Who will we become after we are here?",
    textMode: "emissive",
    scrollWeight: 1.02,
    entryTransitionPct: 0.18,
    holdPct: 0.56,
    exitTransitionPct: 0.26,
    assetSlot: "planetary-civilization",
  },
  {
    id: "galaxy",
    chapterLabel: "Future",
    title: "Future",
    line: "How can we be part of the future?",
    textMode: "starfield",
    scrollWeight: 1.24,
    entryTransitionPct: 0.16,
    holdPct: 0.6,
    exitTransitionPct: 0.24,
    assetSlot: "galaxy-future-field",
  },
];
