import { OriginBeatDefinition } from "./types";

export const originBeats: OriginBeatDefinition[] = [
  {
    id: "spark",
    chapterLabel: "Spark",
    kicker: "Chapter 01",
    title: "Research starts as a systems question.",
    line: "I am pulled toward problems that sit between biology, cognition, design, and the future.",
    detail:
      "Origin opens in a study built from notebooks, instruments, and orbital sketches: a grounded scene for the curiosity that drives the rest of the site.",
    overlayMode: "editorial",
    tags: ["Systems thinking", "Curiosity", "Research direction"],
    scrollWeight: 1.02,
    entryTransitionPct: 0.18,
    holdPct: 0.57,
    exitTransitionPct: 0.25,
    assetSlot: "observatory-workbench",
    palette: {
      backdrop: "#030712",
      accent: "#7dd3fc",
      secondary: "#f59e0b",
      glow: "#38bdf8",
      fog: "#07111f",
      panel: "rgba(5, 11, 23, 0.78)",
      text: "#e6f4ff",
    },
    camera: {
      position: [0.18, 0.28, 6.2],
      target: [0.02, 0.12, 0],
      fov: 38,
      parallax: 0.22,
      drift: 0.18,
      roll: -0.03,
    },
    lighting: {
      ambientIntensity: 0.44,
      keyIntensity: 1.18,
      keyPosition: [2.8, 3.2, 3.4],
      fillIntensity: 0.64,
      fillPosition: [-2.8, 1.6, 2.4],
      rimIntensity: 0.72,
    },
    layerBudget: {
      backgroundDensity: 1.05,
      foregroundDensity: 0.9,
      detailBoost: 1.08,
      bloomStrength: 0.36,
    },
    hotspots: [
      {
        id: "spark-notes",
        label: "Notes",
        title: "The notes are about repair, cognition, and future interfaces.",
        body:
          "The page should read as one research practice, not disconnected interests: longevity, neuroscience, design systems, and future technology all inform each other.",
        tint: "#7dd3fc",
        anchor: [0.26, 0.65],
        mobileAnchor: [0.2, 0.72],
        focusTarget: [-1.15, -0.28, 0.18],
        cameraOffset: [-0.38, -0.1, 0.18],
        subsceneId: "spark-notes-dive",
      },
      {
        id: "spark-orrery",
        label: "Orbit rig",
        title: "The orrery stands in for systems thinking.",
        body:
          "I like questions that require multiple scales to be held together at once. The page should communicate that habit before any single project is introduced.",
        tint: "#f59e0b",
        anchor: [0.66, 0.42],
        mobileAnchor: [0.77, 0.3],
        focusTarget: [0.75, 0.3, 0.2],
        cameraOffset: [0.42, 0.08, -0.14],
        subsceneId: "spark-orrery-dive",
      },
    ],
    subscenes: [
      {
        id: "spark-notes-dive",
        hotspotId: "spark-notes",
        kicker: "Detail Dive",
        label: "Research notebook",
        title: "The notebook connects longevity, cognition, and interface work into one practice.",
        body:
          "Use the dive to read the chapter at desk scale: annotated pages, optics, and instruments should feel like evidence of an ongoing research habit rather than decorative props.",
        progressLabel: "Notebook inspection",
        accent: "#7dd3fc",
        camera: {
          position: [-0.98, -0.12, 3.3],
          target: [-1.08, -0.26, 0.18],
          fov: 26,
          parallax: 0.08,
          drift: 0.06,
          roll: -0.05,
        },
        focusTarget: [-1.08, -0.26, 0.18],
        cameraOffset: [-0.62, -0.08, -1.1],
      },
      {
        id: "spark-orrery-dive",
        hotspotId: "spark-orrery",
        kicker: "Detail Dive",
        label: "Systems orbit",
        title: "The orrery is a literalized systems diagram: multiple scales moving at once.",
        body:
          "In the dive, the rings and brass mechanics should feel precise, slow, and legible. The motion needs to reward scroll with layered orbital changes instead of a generic zoom.",
        progressLabel: "Orrery study",
        accent: "#f59e0b",
        camera: {
          position: [1.22, 0.36, 3.1],
          target: [0.78, 0.28, 0.18],
          fov: 25,
          parallax: 0.08,
          drift: 0.05,
          roll: 0.04,
        },
        focusTarget: [0.78, 0.28, 0.18],
        cameraOffset: [0.7, 0.1, -1.18],
      },
    ],
  },
  {
    id: "biology",
    chapterLabel: "Biology",
    kicker: "Chapter 02",
    title: "Longevity is a repair problem inside living systems.",
    line: "I’m interested in how resilience emerges from layered regulation, sensing, and intervention.",
    detail:
      "This chapter moves from cell-scale material to an authored lab tableau, with translucent volume, metabolic motion, and repair loops that feel alive rather than diagrammatic.",
    overlayMode: "field",
    tags: ["Longevity", "Repair loops", "Regeneration"],
    scrollWeight: 1.18,
    entryTransitionPct: 0.16,
    holdPct: 0.6,
    exitTransitionPct: 0.24,
    assetSlot: "longevity-bio-lab",
    palette: {
      backdrop: "#02120f",
      accent: "#34d399",
      secondary: "#67e8f9",
      glow: "#10b981",
      fog: "#031917",
      panel: "rgba(3, 24, 20, 0.78)",
      text: "#ecfeff",
    },
    camera: {
      position: [-0.12, 0.14, 5.4],
      target: [0, 0.04, 0],
      fov: 36,
      parallax: 0.18,
      drift: 0.14,
      roll: -0.01,
    },
    lighting: {
      ambientIntensity: 0.52,
      keyIntensity: 1.04,
      keyPosition: [2.2, 2.8, 2.6],
      fillIntensity: 0.78,
      fillPosition: [-2.6, 1.2, 2.1],
      rimIntensity: 0.68,
    },
    layerBudget: {
      backgroundDensity: 1.18,
      foregroundDensity: 1.1,
      detailBoost: 1.14,
      bloomStrength: 0.42,
    },
    hotspots: [
      {
        id: "biology-repair",
        label: "Repair loops",
        title: "The scene centers on repair, not immortality mythology.",
        body:
          "The emphasis is on maintenance, adaptation, and the choreography of interventions across scales rather than one silver-bullet breakthrough.",
        tint: "#34d399",
        anchor: [0.38, 0.38],
        mobileAnchor: [0.24, 0.34],
        focusTarget: [-0.36, 0.28, 0.16],
        cameraOffset: [-0.24, 0.06, -0.2],
        subsceneId: "biology-repair-dive",
      },
      {
        id: "biology-signals",
        label: "Signals",
        title: "Diagnostics and signals matter as much as interventions.",
        body:
          "Sensing, regulation, and feedback loops are part of the same story. The visuals should imply systems management rather than generic biotech decoration.",
        tint: "#67e8f9",
        anchor: [0.74, 0.64],
        mobileAnchor: [0.76, 0.74],
        focusTarget: [1.12, -0.22, 0.1],
        cameraOffset: [0.36, -0.06, 0.12],
        subsceneId: "biology-signals-dive",
      },
    ],
    subscenes: [
      {
        id: "biology-repair-dive",
        hotspotId: "biology-repair",
        kicker: "Detail Dive",
        label: "Repair choreography",
        title: "The biological story is about layered maintenance loops, not one miracle intervention.",
        body:
          "The close-up should intensify membrane motion, strand behavior, and reactive lighting so that the system reads as living infrastructure under active repair.",
        progressLabel: "Repair loop pass",
        accent: "#34d399",
        camera: {
          position: [-0.44, 0.38, 3.05],
          target: [-0.3, 0.28, 0.18],
          fov: 24,
          parallax: 0.07,
          drift: 0.05,
        },
        focusTarget: [-0.3, 0.28, 0.18],
        cameraOffset: [-0.24, 0.18, -1.15],
      },
      {
        id: "biology-signals-dive",
        hotspotId: "biology-signals",
        kicker: "Detail Dive",
        label: "Diagnostic column",
        title: "Signals, diagnostics, and intervention logic sit in the same loop.",
        body:
          "This dive should feel slightly more instrument-like: scan bars, calibrated pulses, and measurable change rather than an abstract energy field.",
        progressLabel: "Signal scan",
        accent: "#67e8f9",
        camera: {
          position: [1.44, 0.02, 2.92],
          target: [1.14, -0.18, 0.12],
          fov: 23,
          parallax: 0.07,
          drift: 0.05,
        },
        focusTarget: [1.14, -0.18, 0.12],
        cameraOffset: [0.52, 0.02, -1.18],
      },
    ],
  },
  {
    id: "mind",
    chapterLabel: "Mind",
    kicker: "Chapter 03",
    title: "Cognition is a dynamic architecture, not a static box.",
    line: "I’m interested in memory, prediction, consciousness, and the networked nature of identity.",
    detail:
      "The chapter should feel like a neural atlas rendered as space and light: memory traces, signal travel, and structure without falling back to stock brain imagery.",
    overlayMode: "signal",
    tags: ["Consciousness", "Prediction", "Memory"],
    scrollWeight: 1.08,
    entryTransitionPct: 0.17,
    holdPct: 0.58,
    exitTransitionPct: 0.25,
    assetSlot: "neural-atlas-lab",
    palette: {
      backdrop: "#040916",
      accent: "#a78bfa",
      secondary: "#7dd3fc",
      glow: "#8b5cf6",
      fog: "#07111e",
      panel: "rgba(8, 10, 30, 0.78)",
      text: "#eef2ff",
    },
    camera: {
      position: [0.08, 0.06, 5.9],
      target: [0, 0, 0],
      fov: 37,
      parallax: 0.2,
      drift: 0.16,
      roll: 0.02,
    },
    lighting: {
      ambientIntensity: 0.46,
      keyIntensity: 1.1,
      keyPosition: [2.6, 2.4, 2.7],
      fillIntensity: 0.72,
      fillPosition: [-2.3, 1.4, 2.1],
      rimIntensity: 0.74,
    },
    layerBudget: {
      backgroundDensity: 1.2,
      foregroundDensity: 1.02,
      detailBoost: 1.08,
      bloomStrength: 0.46,
    },
    hotspots: [
      {
        id: "mind-prediction",
        label: "Prediction",
        title: "Prediction is treated as structure, not just metaphor.",
        body:
          "The neural space should imply forecasting, memory, and signal routing. It is a chapter about cognition as architecture rather than disembodied abstraction.",
        tint: "#a78bfa",
        anchor: [0.28, 0.32],
        mobileAnchor: [0.2, 0.28],
        focusTarget: [-0.82, 0.42, 0.2],
        cameraOffset: [-0.34, 0.12, -0.1],
        subsceneId: "mind-prediction-dive",
      },
      {
        id: "mind-memory",
        label: "Memory",
        title: "Memory should feel layered, luminous, and revisable.",
        body:
          "Signal paths and glass planes suggest archived traces that can still move. The goal is a spatial metaphor for thinking, not a scientific illustration.",
        tint: "#7dd3fc",
        anchor: [0.71, 0.58],
        mobileAnchor: [0.77, 0.66],
        focusTarget: [1.02, -0.12, 0.16],
        cameraOffset: [0.38, -0.08, 0.1],
        subsceneId: "mind-memory-dive",
      },
    ],
    subscenes: [
      {
        id: "mind-prediction-dive",
        hotspotId: "mind-prediction",
        kicker: "Detail Dive",
        label: "Prediction lattice",
        title: "Prediction becomes a navigable lattice instead of a static point cloud.",
        body:
          "Use the dive to make the structure denser and more directed. Scroll should feel like travelling through expectations updating across a live network.",
        progressLabel: "Prediction pass",
        accent: "#a78bfa",
        camera: {
          position: [-0.9, 0.44, 3.12],
          target: [-0.82, 0.36, 0.22],
          fov: 24,
          parallax: 0.06,
          drift: 0.05,
          roll: 0.05,
        },
        focusTarget: [-0.82, 0.36, 0.22],
        cameraOffset: [-0.5, 0.16, -1.08],
      },
      {
        id: "mind-memory-dive",
        hotspotId: "mind-memory",
        kicker: "Detail Dive",
        label: "Memory stack",
        title: "Memory is rendered as layered traces that remain editable and alive.",
        body:
          "In the dive, cards, panes, and signal nodes should separate in depth so the user can feel stored traces and retrieval routes as distinct spatial layers.",
        progressLabel: "Memory recall",
        accent: "#7dd3fc",
        camera: {
          position: [1.18, -0.04, 3.02],
          target: [1.02, -0.12, 0.16],
          fov: 24,
          parallax: 0.06,
          drift: 0.05,
          roll: -0.04,
        },
        focusTarget: [1.02, -0.12, 0.16],
        cameraOffset: [0.5, -0.04, -1.12],
      },
    ],
  },
  {
    id: "build",
    chapterLabel: "Build",
    kicker: "Chapter 04",
    title: "I translate ideas into interfaces, prototypes, and systems.",
    line: "Research matters most to me when it becomes usable: tools, environments, and products people can actually move through.",
    detail:
      "This chapter deliberately grounds the page. It should feel like a prototype bench full of interface panes, device mockups, and structured output rather than another abstract field.",
    overlayMode: "editorial",
    tags: ["Interfaces", "Prototyping", "Design systems"],
    scrollWeight: 1.16,
    entryTransitionPct: 0.18,
    holdPct: 0.56,
    exitTransitionPct: 0.26,
    assetSlot: "studio-prototype-bench",
    palette: {
      backdrop: "#080b12",
      accent: "#fb7185",
      secondary: "#38bdf8",
      glow: "#f97316",
      fog: "#0f1720",
      panel: "rgba(14, 18, 29, 0.82)",
      text: "#fff7ed",
    },
    camera: {
      position: [0.24, -0.06, 6.05],
      target: [0.08, -0.04, 0],
      fov: 39,
      parallax: 0.18,
      drift: 0.12,
      roll: -0.02,
    },
    lighting: {
      ambientIntensity: 0.42,
      keyIntensity: 1.08,
      keyPosition: [2.8, 2.2, 2.8],
      fillIntensity: 0.76,
      fillPosition: [-2.4, 1.1, 2.2],
      rimIntensity: 0.78,
    },
    layerBudget: {
      backgroundDensity: 0.9,
      foregroundDensity: 1.14,
      detailBoost: 1.18,
      bloomStrength: 0.34,
    },
    hotspots: [
      {
        id: "build-systems",
        label: "Systems",
        title: "The build chapter should communicate architectural discipline.",
        body:
          "This is where the page signals that the site owner is not only interested in ideas, but in structuring interfaces, interactions, and reusable systems around them.",
        tint: "#38bdf8",
        anchor: [0.3, 0.58],
        mobileAnchor: [0.18, 0.7],
        focusTarget: [-1.02, -0.22, 0.1],
        cameraOffset: [-0.4, -0.08, 0.08],
        subsceneId: "build-systems-dive",
      },
      {
        id: "build-prototypes",
        label: "Prototypes",
        title: "Prototype work should feel active and iterative.",
        body:
          "Screens, cards, and device forms imply motion between concept and implementation. This chapter is the clearest statement that the story is about a researcher-builder.",
        tint: "#fb7185",
        anchor: [0.72, 0.4],
        mobileAnchor: [0.8, 0.34],
        focusTarget: [1.06, 0.24, 0.14],
        cameraOffset: [0.42, 0.08, -0.16],
        subsceneId: "build-prototypes-dive",
      },
    ],
    subscenes: [
      {
        id: "build-systems-dive",
        hotspotId: "build-systems",
        kicker: "Detail Dive",
        label: "Interface system",
        title: "The system view should feel architected: layered panels, motion rules, and reusable structure.",
        body:
          "Use the dive to make grid lines, cards, and signal planes lock into place. Scroll should feel like traversing a live architecture diagram rather than a loose prop arrangement.",
        progressLabel: "System walkthrough",
        accent: "#38bdf8",
        camera: {
          position: [-1.18, -0.18, 3.18],
          target: [-1.04, -0.22, 0.12],
          fov: 24,
          parallax: 0.06,
          drift: 0.05,
          roll: -0.04,
        },
        focusTarget: [-1.04, -0.22, 0.12],
        cameraOffset: [-0.58, -0.08, -1.14],
      },
      {
        id: "build-prototypes-dive",
        hotspotId: "build-prototypes",
        kicker: "Detail Dive",
        label: "Prototype stack",
        title: "Prototype work should feel in-progress, iterative, and materially grounded.",
        body:
          "The dive should emphasize devices, surfaces, and display planes. Scroll should reveal staged iterations rather than simply zooming on a static object.",
        progressLabel: "Prototype pass",
        accent: "#fb7185",
        camera: {
          position: [1.22, 0.22, 3.12],
          target: [1.04, 0.24, 0.14],
          fov: 24,
          parallax: 0.06,
          drift: 0.05,
          roll: 0.04,
        },
        focusTarget: [1.04, 0.24, 0.14],
        cameraOffset: [0.56, 0.1, -1.16],
      },
    ],
  },
  {
    id: "augmentation",
    chapterLabel: "Augment",
    kicker: "Chapter 05",
    title: "Human-machine work matters when it expands agency.",
    line: "I’m interested in augmentation that increases capability, dignity, and healthspan rather than novelty for its own sake.",
    detail:
      "The lab shifts into an augmentation chamber: sensor halos, robotic hardware, and soft medical lighting that suggest practical interfaces between people and machines.",
    overlayMode: "field",
    tags: ["BCI", "Wearables", "Neural interfaces"],
    scrollWeight: 1.04,
    entryTransitionPct: 0.18,
    holdPct: 0.57,
    exitTransitionPct: 0.25,
    assetSlot: "augmentation-chamber",
    palette: {
      backdrop: "#06070f",
      accent: "#22d3ee",
      secondary: "#fda4af",
      glow: "#67e8f9",
      fog: "#0a0f1a",
      panel: "rgba(8, 14, 26, 0.78)",
      text: "#f8fafc",
    },
    camera: {
      position: [-0.18, 0.1, 5.8],
      target: [0, 0.02, 0],
      fov: 37,
      parallax: 0.19,
      drift: 0.13,
      roll: 0.02,
    },
    lighting: {
      ambientIntensity: 0.48,
      keyIntensity: 1.12,
      keyPosition: [2.4, 2.9, 2.4],
      fillIntensity: 0.7,
      fillPosition: [-2.7, 1.4, 2.6],
      rimIntensity: 0.8,
    },
    layerBudget: {
      backgroundDensity: 0.96,
      foregroundDensity: 1.12,
      detailBoost: 1.12,
      bloomStrength: 0.4,
    },
    hotspots: [
      {
        id: "augmentation-wearables",
        label: "Wearables",
        title: "Wearables are framed as sensing and feedback tools.",
        body:
          "This part of the story is about practical augmentation: devices that improve signal, agency, and adaptation rather than purely speculative aesthetics.",
        tint: "#22d3ee",
        anchor: [0.33, 0.38],
        mobileAnchor: [0.21, 0.32],
        focusTarget: [-0.84, 0.26, 0.18],
        cameraOffset: [-0.28, 0.06, -0.12],
        subsceneId: "augmentation-wearables-dive",
      },
      {
        id: "augmentation-bci",
        label: "Interfaces",
        title: "BCI and prosthetic ideas stay grounded in usability.",
        body:
          "The chamber should imply assistive technology, neural links, and precise hardware. The goal is optimistic realism, not cyberpunk costume work.",
        tint: "#fda4af",
        anchor: [0.72, 0.6],
        mobileAnchor: [0.8, 0.72],
        focusTarget: [0.96, -0.16, 0.12],
        cameraOffset: [0.36, -0.04, 0.12],
        subsceneId: "augmentation-bci-dive",
      },
    ],
    subscenes: [
      {
        id: "augmentation-wearables-dive",
        hotspotId: "augmentation-wearables",
        kicker: "Detail Dive",
        label: "Wearable sensor",
        title: "The wearable story is about signal quality, calibration, and lived usefulness.",
        body:
          "The close-up should feel like a careful technical inspection: halos tighten, device surfaces clarify, and the scroll motion reveals sensing passes instead of random neon noise.",
        progressLabel: "Sensor pass",
        accent: "#22d3ee",
        camera: {
          position: [-0.92, 0.22, 3.04],
          target: [-0.82, 0.22, 0.18],
          fov: 24,
          parallax: 0.06,
          drift: 0.05,
          roll: -0.03,
        },
        focusTarget: [-0.82, 0.22, 0.18],
        cameraOffset: [-0.46, 0.08, -1.18],
      },
      {
        id: "augmentation-bci-dive",
        hotspotId: "augmentation-bci",
        kicker: "Detail Dive",
        label: "Interface rig",
        title: "The BCI/prosthetic thread stays practical: precise hardware, clean signal paths, and assistive intent.",
        body:
          "The dive should pull the user into a tighter equipment view where cables, connectors, and luminous guides feel functional rather than costume-like.",
        progressLabel: "Interface scan",
        accent: "#fda4af",
        camera: {
          position: [1.14, -0.1, 3.08],
          target: [0.96, -0.16, 0.12],
          fov: 24,
          parallax: 0.06,
          drift: 0.05,
          roll: 0.03,
        },
        focusTarget: [0.96, -0.16, 0.12],
        cameraOffset: [0.52, -0.06, -1.18],
      },
    ],
  },
  {
    id: "trajectory",
    chapterLabel: "Trajectory",
    kicker: "Chapter 06",
    title: "The long horizon is where all of this points.",
    line: "I want to build research, tools, and stories that help people move toward longer, more capable futures.",
    detail:
      "The finale zooms out without becoming vague: orbital infrastructure, launch paths, and a live horizon that ties the previous chapters into one direction of travel.",
    overlayMode: "signal",
    tags: ["Future tech", "Space", "Long-horizon design"],
    scrollWeight: 1.24,
    entryTransitionPct: 0.16,
    holdPct: 0.6,
    exitTransitionPct: 0.24,
    assetSlot: "orbital-future-bridge",
    palette: {
      backdrop: "#030816",
      accent: "#93c5fd",
      secondary: "#c084fc",
      glow: "#60a5fa",
      fog: "#061125",
      panel: "rgba(5, 14, 28, 0.8)",
      text: "#eff6ff",
    },
    camera: {
      position: [0.12, 0.18, 6.3],
      target: [0, 0.04, 0],
      fov: 39,
      parallax: 0.16,
      drift: 0.12,
      roll: 0.02,
    },
    lighting: {
      ambientIntensity: 0.4,
      keyIntensity: 1.16,
      keyPosition: [2.7, 2.8, 2.9],
      fillIntensity: 0.62,
      fillPosition: [-2.6, 1.6, 2.2],
      rimIntensity: 0.82,
    },
    layerBudget: {
      backgroundDensity: 1.28,
      foregroundDensity: 0.98,
      detailBoost: 1.14,
      bloomStrength: 0.48,
    },
    hotspots: [
      {
        id: "trajectory-horizon",
        label: "Horizon",
        title: "The finale is about direction, not escape.",
        body:
          "Space and future infrastructure appear here as part of a long-horizon practice. The point is where research and design could lead, not generic futurist spectacle.",
        tint: "#93c5fd",
        anchor: [0.24, 0.36],
        mobileAnchor: [0.18, 0.3],
        focusTarget: [-1.02, 0.24, 0.2],
        cameraOffset: [-0.36, 0.08, -0.1],
        subsceneId: "trajectory-horizon-dive",
      },
      {
        id: "trajectory-collaboration",
        label: "Orbit",
        title: "The closing note is about open trajectory and collaboration.",
        body:
          "The orbital structures and signal paths imply future research, tooling, and public-facing work that is still in motion and open to collaboration.",
        tint: "#c084fc",
        anchor: [0.72, 0.56],
        mobileAnchor: [0.82, 0.68],
        focusTarget: [1.04, -0.12, 0.12],
        cameraOffset: [0.4, -0.04, 0.12],
        subsceneId: "trajectory-collaboration-dive",
      },
    ],
    subscenes: [
      {
        id: "trajectory-horizon-dive",
        hotspotId: "trajectory-horizon",
        kicker: "Detail Dive",
        label: "Horizon bridge",
        title: "The long horizon should feel engineered and reachable, not mythical.",
        body:
          "In the dive, orbital structures and the illuminated horizon separate in depth. Scroll should feel like moving through a bridge between present work and future infrastructure.",
        progressLabel: "Horizon pass",
        accent: "#93c5fd",
        camera: {
          position: [-1.06, 0.22, 3.22],
          target: [-1.0, 0.22, 0.2],
          fov: 25,
          parallax: 0.05,
          drift: 0.04,
          roll: -0.03,
        },
        focusTarget: [-1.0, 0.22, 0.2],
        cameraOffset: [-0.54, 0.08, -1.14],
      },
      {
        id: "trajectory-collaboration-dive",
        hotspotId: "trajectory-collaboration",
        kicker: "Detail Dive",
        label: "Orbital signal",
        title: "The final detail is about open motion, public work, and collaboration.",
        body:
          "The dive should reward scroll with a clear signal arc: satellites, rings, and traces should feel like a live network still in motion rather than a frozen final image.",
        progressLabel: "Orbit pass",
        accent: "#c084fc",
        camera: {
          position: [1.18, -0.06, 3.18],
          target: [1.04, -0.12, 0.12],
          fov: 25,
          parallax: 0.05,
          drift: 0.04,
          roll: 0.04,
        },
        focusTarget: [1.04, -0.12, 0.12],
        cameraOffset: [0.56, -0.04, -1.16],
      },
    ],
  },
];
