export const landingTerminalPrompts: string[] = [
  "Initializing interactive showcase...",
  "Electron microscope display matrix online.",
  "Ascending to the stars wasn't meant to be peaceful, it's a fire in a madhouse.",
  "Cell-scale simulation active.",
  "Currently fighting off infection.",
  "rip your browser cache.",
  "This cell probably has a bad infection...",
  "We breathed life into stone, but what gave life to soup?",
  "Do you welcome invaders? How can you know?",
  "Emergence from simple rules.",
  "AI could not one-shot this ;(.",
  "3 billion letters in the code that makes you.",
  "Bioweapon security is a trillion dollar industry.",
  "Trillions of cells... All for you to experience.",
  "Last humans to die, or first to live forever?",
  "Rotate, hover, and click to shape the cell.",
  "01001001 00100000 00111100 00110011 00100000 01111001 01101111 01110101",
  "Do you love often? You should do it more.",
  "Threat eliminated. Deactivating apoptosis.",
  "Nanobots made out of proteins will be the longevity pill.",
  "Isn't it amazing that we can see at all?",
  "Our wetware is pretty insane when you think about it.",
  "You should really play Outer Wilds.",
  "Take a moment to appreciate the Hubble Deep Field.",
  "In a blink of an eye, we will have the capabilities we wrote about for centuries.",
  "Biodiversity needs to be respected, even at the cellular level.",
  "Spend more time with the people who bring many colours to your life.",
  "I hope we keep our humanity when we walk among the stars.",
  "It's super complicated, and then it's obviously simple.",
  "The future is coming whether you like it or not, but you can still shape it.",
  "Product is the best policy. Easiest to implement...",
  "Restoring telomeres... Limiting telomerase activity...",
  "Trying to understand what Kubernetes is...",
  "Hosted on my macbook m1 pro.",
  ":)",
  "Feel free to reach out! There are never enough interesting conversations!",
  "Stll trying to make mobile pretty ;(.",
  "Hi! -Amy <3",
  "I also have a twin brother!",
  "Probably sweating from the hands.",
  "Super excited for terraforming on the biological side: From microbes to megafauna.",
  "So it really is all noise filtering itself, huh?",
  "Everything sings. Can you hear it?",
  "Hear me out: irigate the Australian outback by blowing it up into a canal.",
  "The next humans will be more human than before.",
];
