export const landingTerminalPrompts: string[] = [
  "Initializing interactive showcase...",
  "Quantum display matrix online.",
  "Signal harmonics synced.",
  "Cell-scale simulation active.",
  "Biotic field rendering at full depth.",
  "Pattern engine tracking pointer dynamics.",
  "Emergence sequence ready.",
  "Cognitive atlas loading.",
  "Transhuman trajectory mapper online.",
  "Nanoscopic motion vectors stabilized.",
  "Neural topology index compiled.",
  "Orbit protocol initialized.",
  "Adaptive story timeline prepared.",
  "Dynamic exhibit slot available.",
  "System calibration complete.",
  "Rotate, hover, and click to shape the field.",
];
