import { OriginAssetCreditEntry } from "../types";

export const originAssetCredits: OriginAssetCreditEntry[] = [
  {
    id: "ph-school-desk",
    kind: "model",
    title: "School Desk 01",
    author: "Poly Haven",
    license: "CC0",
    sourceUrl: "https://polyhaven.com/a/school_desk_01",
    attribution: "School Desk 01 by Poly Haven, licensed CC0.",
    usage: ["spark"],
  },
  {
    id: "ph-desk-lamp-arm",
    kind: "model",
    title: "Desk Lamp Arm 01",
    author: "Poly Haven",
    license: "CC0",
    sourceUrl: "https://polyhaven.com/a/desk_lamp_arm_01",
    attribution: "Desk Lamp Arm 01 by Poly Haven, licensed CC0.",
    usage: ["spark", "build"],
  },
  {
    id: "ph-camera-01",
    kind: "model",
    title: "Camera 01",
    author: "Poly Haven",
    license: "CC0",
    sourceUrl: "https://polyhaven.com/a/camera_01",
    attribution: "Camera 01 by Poly Haven, licensed CC0.",
    usage: ["spark", "build"],
  },
  {
    id: "ph-magnifying-glass",
    kind: "model",
    title: "Magnifying Glass 01",
    author: "Poly Haven",
    license: "CC0",
    sourceUrl: "https://polyhaven.com/a/magnifying_glass_01",
    attribution: "Magnifying Glass 01 by Poly Haven, licensed CC0.",
    usage: ["spark", "biology"],
  },
  {
    id: "ph-tool-chest",
    kind: "model",
    title: "Metal Tool Chest",
    author: "Poly Haven",
    license: "CC0",
    sourceUrl: "https://polyhaven.com/a/metal_tool_chest",
    attribution: "Metal Tool Chest by Poly Haven, licensed CC0.",
    usage: ["build", "augmentation"],
  },
  {
    id: "ph-modular-cables",
    kind: "model",
    title: "Modular Electric Cables",
    author: "Poly Haven",
    license: "CC0",
    sourceUrl: "https://polyhaven.com/a/modular_electric_cables",
    attribution: "Modular Electric Cables by Poly Haven, licensed CC0.",
    usage: ["build", "augmentation"],
  },
  {
    id: "ph-signal-hill-dawn",
    kind: "hdri",
    title: "Signal Hill Dawn",
    author: "Poly Haven",
    license: "CC0",
    sourceUrl: "https://polyhaven.com/a/signal_hill_dawn",
    attribution: "Signal Hill Dawn HDRI by Poly Haven, licensed CC0.",
    usage: ["spark"],
  },
  {
    id: "ph-vintage-measuring-lab",
    kind: "hdri",
    title: "Vintage Measuring Lab",
    author: "Poly Haven",
    license: "CC0",
    sourceUrl: "https://polyhaven.com/a/vintage_measuring_lab",
    attribution: "Vintage Measuring Lab HDRI by Poly Haven, licensed CC0.",
    usage: ["biology"],
  },
  {
    id: "ph-moon-lab",
    kind: "hdri",
    title: "Moon Lab",
    author: "Poly Haven",
    license: "CC0",
    sourceUrl: "https://polyhaven.com/a/moon_lab",
    attribution: "Moon Lab HDRI by Poly Haven, licensed CC0.",
    usage: ["mind"],
  },
  {
    id: "ph-empty-workshop",
    kind: "hdri",
    title: "Empty Workshop",
    author: "Poly Haven",
    license: "CC0",
    sourceUrl: "https://polyhaven.com/a/empty_workshop",
    attribution: "Empty Workshop HDRI by Poly Haven, licensed CC0.",
    usage: ["build"],
  },
  {
    id: "ph-industrial-workshop-foundry",
    kind: "hdri",
    title: "Industrial Workshop Foundry",
    author: "Poly Haven",
    license: "CC0",
    sourceUrl: "https://polyhaven.com/a/industrial_workshop_foundry",
    attribution: "Industrial Workshop Foundry HDRI by Poly Haven, licensed CC0.",
    usage: ["augmentation"],
  },
  {
    id: "ph-rogland-clear-night",
    kind: "hdri",
    title: "Rogland Clear Night",
    author: "Poly Haven",
    license: "CC0",
    sourceUrl: "https://polyhaven.com/a/rogland_clear_night",
    attribution: "Rogland Clear Night HDRI by Poly Haven, licensed CC0.",
    usage: ["trajectory"],
  },
];

export const originAssetCreditsById = originAssetCredits.reduce<Record<string, OriginAssetCreditEntry>>(
  (accumulator, entry) => {
    accumulator[entry.id] = entry;
    return accumulator;
  },
  {},
);
