import { OriginAssetManifest } from "../types";

export const originAssetManifest: OriginAssetManifest = {
  "observatory-workbench": {
    slotId: "observatory-workbench",
    supportingModels: [],
    fallbackSceneId: "spark",
    fallbackKind: "observatory",
    materialPreset: "obsidian-brass",
    lodPolicy: "high-desktop",
    transform: {
      position: [0, -0.1, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
    },
    quality: {
      particleMultiplier: 1.04,
      allowBloom: true,
      secondaryProps: false,
      assetScaleByTier: {
        mobile: 0.94,
        balanced: 1,
        ultra: 1.06,
      },
    },
    creditIds: [],
  },
  "longevity-bio-lab": {
    slotId: "longevity-bio-lab",
    supportingModels: [],
    fallbackSceneId: "biology",
    fallbackKind: "biology",
    materialPreset: "bioluminescent-gel",
    lodPolicy: "high-desktop",
    transform: {
      position: [0, 0, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
    },
    quality: {
      particleMultiplier: 1.18,
      allowBloom: true,
      secondaryProps: false,
      assetScaleByTier: {
        mobile: 0.92,
        balanced: 1,
        ultra: 1.08,
      },
    },
    creditIds: [],
  },
  "neural-atlas-lab": {
    slotId: "neural-atlas-lab",
    supportingModels: [],
    fallbackSceneId: "mind",
    fallbackKind: "mind",
    materialPreset: "cortical-glass",
    lodPolicy: "balanced",
    transform: {
      position: [0, 0.06, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
    },
    quality: {
      particleMultiplier: 1.14,
      allowBloom: true,
      secondaryProps: false,
      assetScaleByTier: {
        mobile: 0.9,
        balanced: 1,
        ultra: 1.05,
      },
    },
    creditIds: [],
  },
  "studio-prototype-bench": {
    slotId: "studio-prototype-bench",
    supportingModels: [],
    fallbackSceneId: "build",
    fallbackKind: "build",
    materialPreset: "studio-carbon",
    lodPolicy: "balanced",
    transform: {
      position: [0, -0.08, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
    },
    quality: {
      particleMultiplier: 0.88,
      allowBloom: true,
      secondaryProps: false,
      assetScaleByTier: {
        mobile: 0.92,
        balanced: 1,
        ultra: 1.08,
      },
    },
    creditIds: [],
  },
  "augmentation-chamber": {
    slotId: "augmentation-chamber",
    supportingModels: [],
    fallbackSceneId: "augmentation",
    fallbackKind: "augmentation",
    materialPreset: "surgical-titanium",
    lodPolicy: "balanced",
    transform: {
      position: [0, 0, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
    },
    quality: {
      particleMultiplier: 0.94,
      allowBloom: true,
      secondaryProps: false,
      assetScaleByTier: {
        mobile: 0.9,
        balanced: 1,
        ultra: 1.04,
      },
    },
    creditIds: [],
  },
  "orbital-future-bridge": {
    slotId: "orbital-future-bridge",
    supportingModels: [],
    fallbackSceneId: "trajectory",
    fallbackKind: "trajectory",
    materialPreset: "orbital-composite",
    lodPolicy: "high-desktop",
    transform: {
      position: [0, 0.02, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
    },
    quality: {
      particleMultiplier: 1.2,
      allowBloom: true,
      secondaryProps: false,
      assetScaleByTier: {
        mobile: 0.9,
        balanced: 1,
        ultra: 1.1,
      },
    },
    creditIds: [],
  },
};
